import type { QuizAnswer, GlossaryEntry } from '@/data/types'

export function buildResultsText(
  score: number,
  answers: QuizAnswer[],
  wrong: QuizAnswer[],
): string {
  const pct = answers.length > 0 ? Math.round((score / answers.length) * 100) : 0
  const lines = [
    'hx Knowledge Hub — Quiz Results',
    `Score: ${score}/${answers.length} (${pct}%)`,
    '',
    ...answers.map(
      (a, i) => `${i + 1}. ${a.question} — ${a.isCorrect ? '✓ Correct' : '✗ Wrong'}`,
    ),
  ]
  if (wrong.length > 0) {
    lines.push('', 'Terms to review:')
    wrong.forEach(w => lines.push(`• ${w.term}`))
  }
  return lines.join('\n')
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    }
    throw new Error('Clipboard API unavailable')
  } catch {
    try {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.cssText = 'position:fixed;left:-9999px;top:-9999px;opacity:0'
      document.body.appendChild(ta)
      ta.focus()
      ta.select()
      const ok = document.execCommand('copy')
      document.body.removeChild(ta)
      return ok
    } catch {
      return false
    }
  }
}

export function openPrintWindow(
  score: number,
  answers: QuizAnswer[],
  wrong: QuizAnswer[],
  glossary: GlossaryEntry[],
): void {
  const pct = answers.length > 0 ? Math.round((score / answers.length) * 100) : 0
  const barColor = pct >= 80 ? '#10b981' : pct >= 50 ? '#f59e0b' : '#ef4444'
  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>hx Knowledge Hub — Quiz Results</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:40px;color:#1e293b;max-width:700px;margin:0 auto}
h1{font-size:22px;margin-bottom:4px}
.sub{color:#64748b;font-size:13px;margin-bottom:24px}
.score{font-size:36px;font-weight:700;margin:16px 0 4px}
.pct{color:#64748b;font-size:14px;margin-bottom:24px}
.bar{height:8px;background:#f1f5f9;border-radius:99px;margin-bottom:32px;max-width:280px}
.bar-fill{height:100%;border-radius:99px;background:${barColor}}
h2{font-size:15px;margin:24px 0 12px;padding-bottom:6px;border-bottom:1px solid #e2e8f0}
.item{display:flex;gap:10px;padding:8px 0;font-size:13px;border-bottom:1px solid #f1f5f9}
.ok{color:#10b981}.no{color:#ef4444}
.review{background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:16px;margin-top:16px}
.review h3{font-size:14px;color:#92400e;margin-bottom:10px}
.review-item{margin-bottom:8px}
.review-item strong{font-size:13px}
.review-item p{font-size:12px;color:#64748b;margin-top:2px}
.footer{margin-top:32px;color:#94a3b8;font-size:11px;text-align:center}
@media print{body{padding:20px}}
</style></head><body>
<h1>hx Knowledge Hub — Quiz Results</h1>
<p class="sub">${dateStr}</p>
<div class="score">${score}/${answers.length}</div>
<p class="pct">${pct}% correct</p>
<div class="bar"><div class="bar-fill" style="width:${pct}%"></div></div>

<h2>All answers</h2>
${answers
  .map((a, i) => {
    const full = glossary.find(g => g.term === a.term)
    const correctOpt = full?.quiz?.opts[a.correct] ?? ''
    return `<div class="item"><span class="${a.isCorrect ? 'ok' : 'no'}">${a.isCorrect ? '✓' : '✗'}</span><span>${i + 1}. ${a.question}${!a.isCorrect ? `<br><small style="color:#94a3b8">Correct: ${correctOpt}</small>` : ''}</span></div>`
  })
  .join('')}

${
  wrong.length > 0
    ? `<div class="review"><h3>Terms to review (${wrong.length})</h3>${wrong
        .map(w => {
          const full = glossary.find(g => g.term === w.term)
          return `<div class="review-item"><strong>${w.term}</strong><p>${full?.def ?? ''}</p></div>`
        })
        .join('')}</div>`
    : ''
}

<p class="footer">Generated by hx Knowledge Hub</p>
<script>window.onload=()=>{window.print()}<\/script>
</body></html>`

  const w = window.open('', '_blank')
  if (w) {
    w.document.write(html)
    w.document.close()
  }
}
